/*
 * Author Name:Sanjay
 * Date: 10/4/2022
 * Created With: IntelliJ IDEA Community Edition
 */

package com.niit.jdp.repository;

import com.niit.jdp.model.PlayList;
import com.niit.jdp.model.Song;
import com.niit.jdp.service.DatabaseService;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class PlayListRepository {
    // Creating Database Service object for calling connect method
    DatabaseService databaseService = new DatabaseService();

    // for adding PlayList into dataBase (create play list)
    public void addIntoDatabase(String playListName) {
        //Creates a Statement object for sending SQL statements to the database.
        // SQL statements without parameters are normally executed using Statement objects. If the same SQL
        Connection getConnection = databaseService.connect();
        String query = "Insert into playList values(?);";
        try {
            //Executes the SQL query in this PreparedStatement
            // object and returns the ResultSet object generated by the query.
            PreparedStatement preparedStatement = getConnection.prepareStatement(query);
            preparedStatement.setString(1, playListName);
            int row = preparedStatement.executeUpdate();
            if (row == 1) {
                System.out.println("Play List successful created");
            } else {
                System.out.println("Play List not created");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Show play list (to view play list)
    public List<PlayList> ShowPlayList() {
        String playList = null;
        int count = 0; // ArrayList arr = new ArrayList();
        // arr.add(13);
        // aar.add("sr")
        List<PlayList> playListsName = new ArrayList<>();
        //Creates a Statement object for sending SQL statements to the database.
        // SQL statements without parameters are normally executed using Statement objects.
        // If the same SQL statement is executed many times, it may be more efficient to use a PreparedStatement object.
        Connection getConnection = databaseService.connect();
        String query = "Select * from playList;";
        try {
            //Executes the given SQL statement, which returns a single ResultSet object.
            Statement statement = getConnection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
            while (resultSet.next()) {
                playList = resultSet.getString(1);
                count++;
                playListsName.add(new PlayList(playList, count));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return playListsName;
    }

    //get song from playList
    public List<Song> getSongFromList(int playListId, List<Song> songList) {
        List<Song> getSong = new ArrayList<>();
        //Creates a Statement object for sending SQL statements to the database.
        // SQL statements without parameters are normally executed using Statement objects.
        // If the same SQL statement is executed many times, it may be more efficient to use a PreparedStatement
        Connection getConnection = databaseService.connect();
        String query = "Select * from playList1 where playListId = " + playListId;

        try {
            //Executes the SQL query in this PreparedStatement
            // object and returns the ResultSet object generated by the query.
            PreparedStatement preparedStatement = getConnection.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                int playListIdFromTable = resultSet.getInt(1);
                int songId = resultSet.getInt(2);
                for (Song song : songList) {
                    if (songId == song.getId()) {
                        getSong.add(song);
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return getSong;
    }

    // inserting song into play list( insert song into play List)
    public void insertSongIntoPlayList(int playListId, int songId) {
        //Creates a Statement object for sending SQL statements to the database.
        // SQL statements without parameters are normally executed using Statement objects.
        // If the same SQL statement is executed many times, it may be more efficient to use a PreparedStatement o
        Connection getConnection = databaseService.connect();
        String query = "Insert into playList1 values(?,?);";
        try {
            //Executes the SQL query in this PreparedStatement
            // object and returns the ResultSet object generated by the query.
            PreparedStatement preparedStatement = getConnection.prepareStatement(query);
            preparedStatement.setInt(1, playListId);
            preparedStatement.setInt(2, songId);
            int row = preparedStatement.executeUpdate();
            if (row == 1) {
                System.out.println("Song successful added into list");
            } else {
                System.out.println("Song not added please try again!");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
